[package]
name = "transactions-ledger"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
pretty_assertions = "1.4.1"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"
serde = { version = "1.0.216", features = ["derive"] }
